
CREATE TABLE COP4331.Users ( 
    ID INT NOT NULL AUTO_INCREMENT, 
    DateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    DateLastLoggedIn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    FirstName VARCHAR(50) NOT NULL DEFAULT '', 
    LastName VARCHAR(50) NOT NULL DEFAULT '', 
    Login VARCHAR(50) NOT NULL DEFAULT '', 
    Password VARCHAR(50) NOT NULL DEFAULT '',

    PRIMARY KEY (ID)
) ENGINE = InnoDB;


CREATE TABLE COP4331.Contacts (
    ID INT NOT NULL AUTO_INCREMENT,
    CreatorID INT NOT NULL,
    FirstName VARCHAR(50) NOT NULL DEFAULT '',
    LastName VARCHAR(50) NOT NULL DEFAULT '',
    Email VARCHAR(320) NOT NULL DEFAULT '',
    PhoneNumber VARCHAR(10) NOT NULL DEFAULT '',
    DateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    IsFavorite BOOLEAN NOT NULL DEFAULT False,

    PRIMARY KEY (ID),
    FOREIGN KEY (CreatorID) REFERENCES COP4331.Users(ID) ON DELETE CASCADE
) ENGINE = InnoDB;
